/* 原理对比：每个 git 命令 = 底层做了什么 + 用“复制文件夹”的原始备份法怎么做 + 差别在哪 */
(function (global) {
  'use strict';
  const { abbrev } = global.GitCore;
  const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const A = {
    init: { git: T('在当前目录创建隐藏的 <code>.git</code> 目录：一个空的<b>对象库</b>（objects）、一个<b>引用目录</b>（refs）和一个指向 <code>main</code> 分支的 <code>HEAD</code>。此时还没有任何提交。', 'Creates a hidden <code>.git</code> directory in the current folder: an empty <b>object database</b> (objects), a <b>refs directory</b> (refs) and a <code>HEAD</code> pointing at the <code>main</code> branch. There are no commits yet.'), folder: T('<code>mkdir 备份/</code> —— 先建一个放备份的文件夹。', '<code>mkdir backups/</code>: first make a folder to hold the backups.'), diff: T('.git 就是那个“备份文件夹”，只不过它按内容哈希存储，而不是按文件名。', '.git is that “backups folder”, except it stores things by content hash instead of by file name.') },
    config: { git: T('把键值对写进 <code>.git/config</code>（或 <code>--global</code> 时写进 <code>~/.gitconfig</code>）。提交时会把 user.name / user.email 写进每个 commit 对象。', 'Writes key/value pairs into <code>.git/config</code> (or <code>~/.gitconfig</code> with <code>--global</code>). When you commit, user.name / user.email get written into every commit object.'), folder: T('在每个备份文件夹里手写一张纸条：“这是谁改的”。', 'Leave a handwritten note in every backup folder: “changed by …”.'), diff: T('git 把作者信息固化在提交里，永远可查（git log / git blame）。', 'git bakes the author into each commit, so you can always look it up (git log / git blame).') },
    add: { git: T('读取文件内容，算出 SHA-1，把内容存成 <b>blob 对象</b>（<code>.git/objects/xx/yyyy…</code>，相同内容只存一份），并在<b>暂存区（index）</b>里登记“路径 → blob 哈希”。此时还没有提交。', 'Reads the file, computes its SHA-1, stores the content as a <b>blob object</b> (<code>.git/objects/xx/yyyy…</code>; identical content is stored only once) and records “path → blob hash” in the <b>staging area (index)</b>. Nothing is committed yet.'), folder: T('把要备份的文件先复制到一个“待打包”文件夹里。', 'Copy the files you want to back up into a “to be packed” folder first.'), diff: T('暂存区让你可以<b>只挑一部分修改</b>进入下一次快照；而且内容一旦 add 就进了对象库，即使你之后改坏了工作区，add 过的版本也还能找回。', 'The staging area lets you <b>pick just some of your changes</b> for the next snapshot. And once content is added it lives in the object database, so even if you later break the file in your working tree, the added version can still be recovered.') },
    commit: { git: T('① 把暂存区打包成 <b>tree 对象</b>（目录快照）；② 创建 <b>commit 对象</b>：指向这棵 tree、指向父提交、记录作者/时间/说明；③ 把当前分支指针（<code>refs/heads/main</code>）前移到新提交；④ 在 reflog 里记一笔。', '① Packs the staging area into a <b>tree object</b> (a snapshot of the directory); ② creates a <b>commit object</b> pointing to that tree and to the parent commit, recording author/time/message; ③ moves the current branch pointer (<code>refs/heads/main</code>) forward to the new commit; ④ adds an entry to the reflog.'), folder: T('<code>cp -r project 备份/2026-01-05_v3/</code>，再在 notes.txt 里写一行“v3：修了登录 bug”。', '<code>cp -r project backups/2026-01-05_v3/</code>, then add a line to notes.txt: “v3: fixed the login bug”.'), diff: T('<b>没变的文件不会被再复制一次</b>：新 tree 直接引用旧 blob。每个快照有唯一哈希（内容变一个字节哈希就变），并且记住了“上一个快照是谁”，所以历史是一条链而不是一堆散乱的文件夹。', '<b>Unchanged files are not copied again</b>: the new tree simply points at the old blobs. Every snapshot has a unique hash (change one byte and the hash changes) and remembers which snapshot came before it, so history is a chain, not a heap of loose folders.') },
    status: { git: T('同时对比三棵树：<b>HEAD 提交的 tree</b> ↔ <b>暂存区</b>（得到“Changes to be committed”）、<b>暂存区</b> ↔ <b>工作区</b>（得到“Changes not staged”），工作区里暂存区没登记的就是 Untracked。', 'Compares the three trees at once: <b>HEAD\'s tree</b> ↔ <b>staging area</b> (gives “Changes to be committed”), <b>staging area</b> ↔ <b>working tree</b> (gives “Changes not staged”); anything in the working tree that the index doesn\'t know about is Untracked.'), folder: T('<code>diff -r project 备份/最新的那个/</code>，逐个文件看有没有变。', '<code>diff -r project backups/the-latest-one/</code> and check file by file whether anything changed.'), diff: T('因为有哈希，git 对比时只比 40 位哈希，不用逐字节读文件；而且能区分“改了但还没决定要不要备份”（未暂存）和“决定了要备份”（已暂存）。', 'Thanks to hashes, git only compares 40-character hashes instead of reading every byte. It also separates “changed, but not yet decided to back up” (unstaged) from “decided to back up” (staged).') },
    diff: { git: T('对两个版本的 blob 做逐行比较（最长公共子序列），输出统一 diff 格式：<code>-</code> 是删掉的行，<code>+</code> 是新增的行。不带参数比较工作区 ↔ 暂存区，<code>--staged</code> 比较暂存区 ↔ HEAD。', 'Compares two versions of a blob line by line (longest common subsequence) and prints a unified diff: <code>-</code> lines were removed, <code>+</code> lines were added. With no arguments it compares working tree ↔ staging area; <code>--staged</code> compares staging area ↔ HEAD.'), folder: T('<code>diff 备份/v2/app.js 备份/v3/app.js</code>', '<code>diff backups/v2/app.js backups/v3/app.js</code>'), diff: T('一样的算法！只是 git 知道“该和哪个版本比”，不用你去翻文件夹。', 'Same algorithm! git just knows which version to compare against, so you don\'t have to dig through folders.') },
    log: { git: T('从 HEAD 指向的提交出发，顺着每个 commit 里的 <code>parent</code> 指针一路往回走，按时间排序输出。<code>--graph</code> 把多个父指针画成分叉。', 'Starts at the commit HEAD points to and walks back along each commit\'s <code>parent</code> pointer, printing in time order. <code>--graph</code> draws multiple parents as forks.'), folder: T('<code>ls -t 备份/</code> 再打开 notes.txt 一条条看说明。', '<code>ls -t backups/</code>, then open notes.txt and read the notes one by one.'), diff: T('备份文件夹之间没有“谁是谁的上一版”的信息，分支/合并的关系完全靠人记；git 的历史是一张有向无环图。', 'Backup folders don\'t know which one came before which; branch and merge relationships live only in your head. git history is a directed acyclic graph.') },
    show: { git: T('找到对象，按类型打印：commit 打印元信息 + 与父提交的 diff；<code>rev:path</code> 形式则直接读出那个版本里的文件内容。', 'Finds the object and prints it by type: for a commit, the metadata plus the diff against its parent; the <code>rev:path</code> form reads that file straight out of that version.'), folder: T('打开某个备份文件夹看看里面的文件。', 'Open a backup folder and look at the files inside.'), diff: T('不用解压/复制，直接从对象库读。', 'No unpacking or copying: it reads straight from the object database.') },
    branch: { git: T('<b>分支只是一个 41 字节的文件</b>：<code>.git/refs/heads/&lt;名字&gt;</code>，内容是一个提交哈希。创建分支 = 写这个文件，删除分支 = 删这个文件。提交内容一个字节都不复制。', '<b>A branch is just a 41-byte file</b>: <code>.git/refs/heads/&lt;name&gt;</code>, containing a commit hash. Creating a branch = writing that file; deleting a branch = deleting it. Not a single byte of your files is copied.'), folder: T('<code>cp -r project project_新功能/</code> —— 整个项目复制一份，在副本里改。', '<code>cp -r project project_new-feature/</code>: copy the whole project and make your changes in the copy.'), diff: T('文件夹方案分支越多磁盘越炸，而且两份文件夹之后很难合回去；git 的分支创建/切换是 O(1) 的，“便宜到可以随便开”。', 'With folders, every branch eats more disk, and two folders are hard to bring back together later. git branches are O(1) to create and switch, “cheap enough to open on a whim”.') },
    checkout: { git: T('① 把 HEAD 改成指向目标分支（或直接指向某个提交 = detached HEAD）；② 把工作区和暂存区里<b>在两个提交之间有差异的文件</b>替换成目标版本（没差异的文件和你未提交的修改保持不动；会被覆盖的修改则拒绝切换）。', '① Points HEAD at the target branch (or straight at a commit = detached HEAD); ② replaces the files <b>that differ between the two commits</b> in the working tree and staging area with the target version (identical files and your uncommitted changes are left alone; if a change would be overwritten, the switch is refused).'), folder: T('<code>cd ../project_新功能/</code>，在不同的文件夹之间跳来跳去。', '<code>cd ../project_new-feature/</code> and jump back and forth between folders.'), diff: T('git 让所有分支共用同一个工作目录，切换时只改动“有差异”的文件；代价是切换前要处理好未提交的修改（提交或 stash）。', 'git lets all branches share one working directory and only touches the files that differ when switching; the price is that you must deal with uncommitted changes first (commit or stash them).') },
    switch: 'checkout', restore: { git: T('<code>git restore 文件</code>：用暂存区里的 blob 覆盖工作区文件；<code>--staged</code>：用 HEAD 里的版本覆盖暂存区登记（工作区不动）。', '<code>git restore &lt;file&gt;</code>: overwrites the working-tree file with the blob from the staging area; <code>--staged</code>: overwrites the staging-area entry with the version from HEAD (the working tree is untouched).'), folder: T('<code>cp 备份/最新/app.js project/app.js</code> 把备份里的版本抄回来。', '<code>cp backups/latest/app.js project/app.js</code>: copy the backed-up version back.'), diff: T('本质相同，只是 git 精确知道“最近一次登记的版本”在哪。注意：<b>未 add 过的修改被 restore 后无法找回</b>，因为它从未进过对象库。', 'Same idea, except git knows exactly where the “last recorded version” is. Careful: <b>changes you never added can\'t be recovered after a restore</b>, because they never made it into the object database.') },
    merge: { git: T('① 找两条分支的<b>共同祖先</b>（merge base）；② 若当前分支就是祖先 → <b>快进</b>（只把指针挪过去）；③ 否则对每个文件做<b>三方比较</b>（祖先/我方/对方）：只有一方改过的直接采用，两方都改了不同区域的自动拼接，改了同一区域的标记为冲突；④ 生成一个有<b>两个父提交</b>的合并提交。', '① Finds the <b>common ancestor</b> of the two branches (the merge base); ② if the current branch is that ancestor → <b>fast-forward</b> (just move the pointer); ③ otherwise does a <b>three-way comparison</b> for every file (ancestor / ours / theirs): changes made on only one side are taken as-is, changes to different regions are combined automatically, and changes to the same region are marked as conflicts; ④ creates a merge commit with <b>two parents</b>.'), folder: T('把两个人各自的文件夹摆在一起，逐个文件肉眼比较，把对方改的地方手抄过来。没有“祖先版本”作参照，根本分不清“是他改了还是我改了”。', 'Put both people\'s folders side by side, compare every file by eye and copy the other person\'s edits over by hand. Without an “ancestor version” as a reference, you can\'t even tell whether they changed something or you did.'), diff: T('三方合并的关键是<b>知道共同起点</b>。有了它，绝大多数合并可以自动完成，只有真正“同一处各改各的”才需要人来决定。', 'The key to a three-way merge is <b>knowing the common starting point</b>. With it, most merges happen automatically; only when both sides changed the same spot does a human need to decide.') },
    rebase: { git: T('① 找到当前分支相对目标分支的“独有提交”；② 把 HEAD 移到目标分支顶端；③ 把独有提交<b>逐个重放</b>（等价于依次 cherry-pick），每次生成<b>新的提交</b>（哈希会变，因为父提交变了）；④ 最后把分支指针指向新的顶端。', '① Finds the commits that exist only on the current branch; ② moves HEAD to the tip of the target branch; ③ <b>replays</b> those commits one by one (like cherry-picking them in order), each time creating a <b>new commit</b> (the hash changes because the parent changed); ④ finally points the branch at the new tip.'), folder: T('从对方最新的文件夹重新复制一份，然后把自己改过的地方一处一处手工再抄一遍。', 'Make a fresh copy of the other person\'s latest folder, then redo every one of your own edits by hand, one at a time.'), diff: T('结果是<b>一条直线的历史</b>，没有合并提交。代价：历史被改写，所以<b>已经推送给别人的提交不要 rebase</b>。', 'The result is <b>a straight line of history</b> with no merge commit. The price: history is rewritten, so <b>never rebase commits you have already pushed to others</b>.') },
    'cherry-pick': { git: T('取出目标提交与其父提交的差异（一个补丁），三方合并到当前 HEAD 上，生成一个内容相同但哈希不同的新提交。', 'Takes the difference between the target commit and its parent (a patch), three-way merges it onto the current HEAD, and creates a new commit with the same changes but a different hash.'), folder: T('从别人的文件夹里，只把某一次修改涉及的几行手抄到自己的文件里。', 'From someone else\'s folder, copy by hand just the few lines touched by one particular change.'), diff: T('git 知道“那一次修改”具体动了哪些行，而文件夹备份只有整体文件，看不出单次改动。', 'git knows exactly which lines “that one change” touched; folder backups only have whole files, so single changes are invisible.') },
    revert: { git: T('把目标提交的差异<b>反过来</b>应用（相当于打一个反向补丁），生成一个新提交。原提交仍在历史里。', 'Applies the target commit\'s changes <b>in reverse</b> (like applying an inverse patch) and creates a new commit. The original commit stays in history.'), folder: T('把那次改动的行手工改回去，再备份一份新的。', 'Change the lines from that edit back by hand, then make another backup.'), diff: T('因为历史没有被改写，<b>已经推送的提交也可以安全地 revert</b>；这是撤销“公共历史”的正确方式。', 'Since history isn\'t rewritten, <b>even pushed commits can be safely reverted</b>; this is the right way to undo “public” history.') },
    reset: { git: T('<code>--soft</code>：只移动分支指针；<code>--mixed</code>（默认）：再把暂存区重置成目标提交的 tree；<code>--hard</code>：连工作区也覆盖。被“甩掉”的提交并不会被删除，仍在对象库里，reflog 记得它们。', '<code>--soft</code>: only moves the branch pointer; <code>--mixed</code> (default): also resets the staging area to the target commit\'s tree; <code>--hard</code>: overwrites the working tree too. The commits you “drop” are not deleted: they remain in the object database and the reflog remembers them.'), folder: T('把 notes.txt 的最后几行划掉，假装那几次备份不存在（--hard 相当于顺手把文件夹也删了）。', 'Cross out the last few lines of notes.txt and pretend those backups never happened (--hard is like deleting the folders too while you\'re at it).'), diff: T('reset 移动的是指针，对象还在，30 天内通过 reflog 都能找回。真删文件夹就真没了。', 'reset moves a pointer; the objects are still there and can be recovered through the reflog for 30 days (by default). Actually deleting a folder means it\'s gone for good.') },
    stash: { git: T('把当前暂存区和工作区分别打包成两个临时提交，挂在 <code>refs/stash</code> 上，然后把工作区恢复成 HEAD 的样子。<code>pop</code> 时做一次三方合并把改动放回来。', 'Packs the current staging area and working tree into two temporary commits hung on <code>refs/stash</code>, then resets the working tree to look like HEAD. <code>pop</code> does a three-way merge to bring the changes back.'), folder: T('把改了一半的文件复制到“临时”文件夹，再把项目还原成备份的样子；回头再抄回来。', 'Copy your half-edited files into a “temp” folder, restore the project from the backup, and copy them back later.'), diff: T('本质就是一次临时快照，stash 就是提交，只是不挂在任何分支上。', 'It\'s really just a temporary snapshot: a stash is a commit that isn\'t on any branch.') },
    tag: { git: T('在 <code>refs/tags/</code> 下写一个指向提交的引用（轻量标签），<code>-a</code> 时再多创建一个带说明/签名者的 tag 对象。标签不会随提交移动。', 'Writes a ref under <code>refs/tags/</code> pointing at a commit (a lightweight tag); with <code>-a</code> it also creates a tag object holding a message and the tagger. Tags don\'t move when you commit.'), folder: T('把某个备份文件夹改名成 <code>release_v1.0</code>。', 'Rename a backup folder to <code>release_v1.0</code>.'), diff: T('标签是给某个快照起的“永久名字”，分支则是会随提交移动的“指针”。', 'A tag is a “permanent name” for one snapshot, whereas a branch is a “pointer” that moves along as you commit.') },
    reflog: { git: T('HEAD 和每个分支每次移动都会追加一行到 <code>.git/logs/</code> 里。reflog 就是打印这份日志，所以“不小心 reset 掉/删掉分支”的提交都能顺着它找回。', 'Every time HEAD or a branch moves, a line is appended under <code>.git/logs/</code>. reflog prints that log, which is why commits lost to an accidental reset or branch deletion can be found again through it.'), folder: T('回收站——但回收站只对“删除”有效，对“改坏了”无能为力。', 'The recycle bin, except a recycle bin only helps with “deleted”, not with “broke it”.'), diff: T('reflog 是本地的安全网（默认保留 90 天），不会被推送到远程。', 'The reflog is a local safety net (kept for 90 days by default) and is never pushed to a remote.') },
    rm: { git: T('从暂存区删除登记（<code>--cached</code> 时保留工作区文件），这样下一次提交的 tree 就不再包含它。历史提交里文件仍然存在。', 'Removes the entry from the staging area (with <code>--cached</code> the working-tree file is kept), so the next commit\'s tree no longer contains it. The file still exists in older commits.'), folder: T('从项目文件夹删掉文件，旧备份里当然还在。', 'Delete the file from the project folder; old backups still have it, of course.'), diff: T('git 的删除也是一次可追溯的变更；用 <code>git checkout &lt;旧提交&gt; -- 文件</code> 随时拿回来。', 'Deleting in git is also a traceable change; get the file back anytime with <code>git checkout &lt;old commit&gt; -- &lt;file&gt;</code>.') },
    mv: { git: T('暂存区里把旧路径的登记换成新路径（blob 不变），工作区改名。git 是通过内容相同推断出“这是重命名”的。', 'In the staging area, the entry for the old path is replaced by the new path (the blob is unchanged), and the file is renamed in the working tree. git infers “this is a rename” because the content is the same.'), folder: T('改文件名，然后备份时又整个复制一份。', 'Rename the file, then copy the whole thing again at the next backup.'), diff: T('内容没变就不会重复存储，重命名的成本是零。', 'Unchanged content is never stored twice, so a rename costs nothing.') },
    blame: { git: T('对文件逐行倒着追溯：从 HEAD 开始比较每个提交与其父提交，某一行第一次出现的那个提交就是它的“作者”。', 'Traces the file backwards line by line: starting at HEAD it compares each commit with its parent; the commit where a line first appears is that line\'s “author”.'), folder: T('打开一个个备份文件夹逐行对比，直到找到这一行第一次出现的那份。', 'Open backup folders one by one and compare line by line until you find the first copy that contains the line.'), diff: T('git 有了 diff 和父链，这个过程可以自动完成。', 'With diffs and the parent chain, git can do all of this automatically.') },
    bisect: { git: T('在“已知好”和“已知坏”之间的提交里<b>二分查找</b>：每次检出中间的提交让你测试，根据 good/bad 缩小范围，log2(N) 次就能定位引入 bug 的提交。', '<b>Binary search</b> through the commits between a “known good” and a “known bad” one: each step checks out the middle commit for you to test, and good/bad halves the range, so log2(N) steps find the commit that introduced the bug.'), folder: T('把几十个备份文件夹一个个拷回去跑测试。', 'Copy dozens of backup folders back one by one and run the tests on each.'), diff: T('因为提交是有序的链，git 可以二分；100 个提交只要 7 次测试。', 'Commits form an ordered chain, so git can bisect: 100 commits need only 7 tests.') },
    remote: { git: T('在 <code>.git/config</code> 里记一条 <code>[remote "origin"] url = …</code>，仅仅是个地址别名。', 'Records <code>[remote "origin"] url = …</code> in <code>.git/config</code>: nothing more than a nickname for an address.'), folder: T('记下服务器地址：“备份放在 192.168.1.5:/backups/”。', 'Write down the server address: “backups live at 192.168.1.5:/backups/”.'), diff: T('远程仓库就是另一台机器上的 .git，结构完全一样（裸仓库连工作区都没有）。', 'A remote repository is just a .git on another machine with exactly the same structure (a bare one doesn\'t even have a working tree).') },
    clone: { git: T('创建一个新的 .git，把远程的<b>全部对象</b>和分支复制过来（分支存成 <code>refs/remotes/origin/*</code>），创建本地 <code>main</code> 跟踪 <code>origin/main</code>，然后检出工作区。', 'Creates a new .git, copies <b>all objects</b> and branches from the remote (branches are stored as <code>refs/remotes/origin/*</code>), creates a local <code>main</code> that tracks <code>origin/main</code>, and checks out the working tree.'), folder: T('<code>scp -r 服务器:/backups/project ./</code> 把整个备份文件夹拖下来。', '<code>scp -r server:/backups/project ./</code>: drag the whole backups folder down.'), diff: T('clone 之后你拥有<b>完整历史</b>，不联网也能查看每个版本、提交、开分支，这就是“分布式”的含义。', 'After cloning you have the <b>complete history</b>: you can view every version, commit and branch without a network connection. That\'s what “distributed” means.') },
    fetch: { git: T('和远程比较引用，把本地没有的对象下载下来，只更新 <code>refs/remotes/origin/*</code>（远程跟踪分支）。你自己的分支和工作区<b>纹丝不动</b>。', 'Compares refs with the remote, downloads the objects you don\'t have, and only updates <code>refs/remotes/origin/*</code> (remote-tracking branches). Your own branches and working tree <b>don\'t move an inch</b>.'), folder: T('把服务器上的最新备份文件夹下载到本地，但先不动自己的项目。', 'Download the latest backup folder from the server, but don\'t touch your own project yet.'), diff: T('fetch 是安全的“先看看别人做了什么”，之后再决定 merge 还是 rebase。', 'fetch is the safe “let\'s see what others did first”; after that you decide whether to merge or rebase.') },
    pull: { git: T('= <code>git fetch</code> + <code>git merge origin/main</code>（或 <code>--rebase</code> 时 + <code>git rebase origin/main</code>）。历史分叉时 git 会要求你明确选择合并策略。', '= <code>git fetch</code> + <code>git merge origin/main</code> (or with <code>--rebase</code>: + <code>git rebase origin/main</code>). When histories have diverged, git asks you to choose a strategy explicitly.'), folder: T('下载别人的文件夹，然后人肉把差异合进自己的。', 'Download the other person\'s folder, then merge the differences into yours by hand.'), diff: T('合并逻辑和本地分支合并完全一样，远程并不特殊。', 'The merge logic is exactly the same as merging local branches; remotes aren\'t special.') },
    push: { git: T('把本地分支指向的提交及其对象上传，然后请求远程把 <code>refs/heads/main</code> 挪到新提交。远程<b>只接受快进</b>（新提交必须包含远程当前的提交），否则拒绝——这是防止你覆盖别人工作的保护机制。', 'Uploads the commit your local branch points to plus its objects, then asks the remote to move <code>refs/heads/main</code> to the new commit. The remote <b>only accepts fast-forwards</b> (the new commit must contain the remote\'s current commit) and rejects anything else: this protects you from overwriting other people\'s work.'), folder: T('把自己的文件夹上传覆盖服务器上的。两个人同时传，后传的直接把先传的覆盖掉，没人知道。', 'Upload your folder over the one on the server. If two people upload at once, the second silently overwrites the first and nobody notices.'), diff: T('“非快进即拒绝”让并发协作变得安全；<code>--force</code> 就是关掉这个保护。', '“Reject anything that isn\'t a fast-forward” makes concurrent collaboration safe; <code>--force</code> switches that protection off.') },
    'cat-file': { git: T('直接读对象库：<code>-t</code> 看类型（blob/tree/commit/tag），<code>-p</code> 打印内容。这就是 git 的全部“数据库”。', 'Reads the object database directly: <code>-t</code> shows the type (blob/tree/commit/tag), <code>-p</code> prints the content. That\'s git\'s entire “database”.'), folder: T('打开备份文件夹看文件。', 'Open a backup folder and look at the files.'), diff: T('看到 tree 里一行行的“模式 类型 哈希 文件名”，就理解了快照是怎么组成的。', 'Once you see a tree\'s lines of “mode type hash filename”, you understand how a snapshot is put together.') },
    'ls-files': { git: T('打印暂存区（index）里登记的所有路径（<code>-s</code> 连哈希一起）。', 'Lists every path recorded in the staging area (index) (<code>-s</code> includes the hashes).'), folder: T('看“待打包”文件夹里有什么。', 'Look at what\'s in the “to be packed” folder.'), diff: '' },
    clean: { git: T('删除工作区中未跟踪（且未被 .gitignore 忽略）的文件。因为它们从未进过对象库，<b>删了就真没了</b>。', 'Deletes untracked files (not ignored by .gitignore) from the working tree. They were never in the object database, so <b>once deleted they\'re really gone</b>.'), folder: T('手动删掉编译产物之类的杂物。', 'Manually delete build output and other clutter.'), diff: '' },
    gc: { git: T('清理不可达且不在 reflog 里的对象，把松散对象打包压缩。', 'Removes objects that are unreachable and not in the reflog, and packs loose objects into compressed packs.'), folder: T('清空回收站。', 'Empty the recycle bin.'), diff: '' },
    fsck: { git: T('检查对象库完整性，列出“悬空”（没有任何引用指向）的提交。', 'Checks the integrity of the object database and lists “dangling” commits (no ref points to them).'), folder: T('找出没记在 notes.txt 里的备份文件夹。', 'Find the backup folders that were never written down in notes.txt.'), diff: '' },
  };

  function explain(argv, trace, repo) {
    if (!argv || argv[0] !== 'git') return null;
    let sub = argv[1];
    if (!sub) return null;
    let a = A[sub];
    if (typeof a === 'string') a = A[a];
    if (!a) return { title: 'git ' + sub, git: T('（这个命令暂无原理说明）', '(No explanation for this command yet.)'), folder: '', diff: '', trace: traceHtml(trace, repo) };
    return { title: argv.slice(0, 2).join(' '), git: a.git, folder: a.folder, diff: a.diff, trace: traceHtml(trace, repo) };
  }

  function traceHtml(trace, repo) {
    if (!trace || !trace.length) return '';
    const items = [];
    const objs = trace.filter(t => t.kind === 'object');
    const counts = {};
    for (const o of objs) counts[o.type] = (counts[o.type] || 0) + 1;
    if (objs.length) items.push(T(`新建对象：${Object.entries(counts).map(([t, n]) => `<b>${n}</b> 个 ${t}`).join('，')}`, `New objects: ${Object.entries(counts).map(([t, n]) => `<b>${n}</b> ${t}${n === 1 ? '' : 's'}`).join(', ')}`) + `<div class="trace-objs">${objs.slice(0, 8).map(o => `<span class="obj obj-${o.type}" title="${o.hash}">${o.type} ${abbrev(o.hash)}</span>`).join(' ')}${objs.length > 8 ? ' …' : ''}</div>`);
    for (const t of trace) {
      if (t.kind === 'ref') {
        const name = t.ref.replace('refs/heads/', T('分支 ', 'branch ')).replace('refs/tags/', T('标签 ', 'tag ')).replace('refs/remotes/', T('远程跟踪分支 ', 'remote-tracking branch '));
        if (t.renamedFrom) items.push(T(`引用重命名：${esc(t.renamedFrom)} → ${esc(t.ref.replace('refs/heads/', ''))}`, `Renamed ref: ${esc(t.renamedFrom)} → ${esc(t.ref.replace('refs/heads/', ''))}`));
        else if (!t.new) items.push(T(`删除引用 <b>${esc(name)}</b>（原指向 ${abbrev(t.old)}）`, `Deleted ref <b>${esc(name)}</b> (was ${abbrev(t.old)})`));
        else if (!t.old) items.push(T(`创建引用 <b>${esc(name)}</b> → ${abbrev(t.new)}`, `Created ref <b>${esc(name)}</b> → ${abbrev(t.new)}`));
        else items.push(T(`移动引用 <b>${esc(name)}</b>：${abbrev(t.old)} → ${abbrev(t.new)}`, `Moved ref <b>${esc(name)}</b>: ${abbrev(t.old)} → ${abbrev(t.new)}`));
      } else if (t.kind === 'head') items.push(t.detached ? T(`HEAD 直接指向提交 ${abbrev(t.to)}（detached）`, `HEAD points directly at commit ${abbrev(t.to)} (detached)`) : `HEAD → refs/heads/${esc(t.to)}`);
      else if (t.kind === 'index' && t.paths && t.paths.length) items.push(T(`暂存区更新：${t.paths.slice(0, 6).map(esc).join(', ')}${t.paths.length > 6 ? ' …' : ''}`, `Staging area (index) updated: ${t.paths.slice(0, 6).map(esc).join(', ')}${t.paths.length > 6 ? ' …' : ''}`));
      else if (t.kind === 'init') items.push(T(`创建 ${t.bare ? '裸仓库' : '.git 目录'}：objects/、refs/heads/、HEAD → refs/heads/main`, `Created ${t.bare ? 'a bare repository' : 'the .git directory'}: objects/, refs/heads/, HEAD → refs/heads/main`));
      else if (t.kind === 'clone') items.push(T(`从 ${esc(t.url)} 复制了 ${t.objects || 0} 个对象，创建 refs/remotes/origin/*`, `Copied ${t.objects || 0} object${t.objects === 1 ? '' : 's'} from ${esc(t.url)} and created refs/remotes/origin/*`));
      else if (t.kind === 'config') items.push(T(`写入配置 ${esc(t.key)} = ${esc(t.value)}${t.global ? '（全局 ~/.gitconfig）' : '（.git/config）'}`, `Wrote config ${esc(t.key)} = ${esc(t.value)}${t.global ? ' (global ~/.gitconfig)' : ' (.git/config)'}`));
      else if (t.kind === 'stash') items.push(T(`创建 stash 提交 ${abbrev(t.hash)}，挂到 refs/stash`, `Created stash commit ${abbrev(t.hash)} on refs/stash`));
    }
    if (!items.length) return '';
    return `<ul class="trace">${items.map(i => `<li>${i}</li>`).join('')}</ul>`;
  }

  // 快照文件夹视图：把每个提交画成“一个备份文件夹”，标出哪些文件是共享的（没有重复存储）
  function snapshotsHtml(repo, limit = 8) {
    const head = repo.headHash();
    if (!head) return `<p class="muted">${T('还没有提交。提交之后，这里会把每个提交画成一个“备份文件夹”。', 'No commits yet. Once you commit, each commit is drawn here as a “backup folder”.')}</p>`;
    const list = repo.revList([head]).slice(0, limit);
    let fullCopyBytes = 0; const blobs = new Set();
    const all = repo.revList([...repo.refs.values()].map(h => repo.peel(h)).concat([head]));
    for (const h of all) { const t = repo.treeOfCommit(h); for (const [, bh] of t) { fullCopyBytes += global.GitCore.byteLen(repo.blobContent(bh)); blobs.add(bh); } }
    let uniqueBytes = 0; for (const b of blobs) uniqueBytes += global.GitCore.byteLen(repo.blobContent(b));
    const cards = list.map((h, i) => {
      const c = repo.getCommit(h);
      const t = repo.treeOfCommit(h);
      const pt = repo.treeOfCommit(c.parents[0] || null);
      const files = [...t].sort().map(([p, bh]) => {
        const same = pt.get(bh === undefined ? '' : p) === bh;
        return `<li class="${same ? 'shared' : 'changed'}"><span class="fname">${esc(p)}</span><span class="fhash">${abbrev(bh)}</span>${same ? `<span class="tag-shared">${T('共享', 'shared')}</span>` : `<span class="tag-new">${T('新 blob', 'new blob')}</span>`}</li>`;
      }).join('');
      const deleted = [...pt.keys()].filter(p => !t.has(p)).map(p => `<li class="deleted"><span class="fname">${esc(p)}</span><span class="tag-del">${T('已删', 'deleted')}</span></li>`).join('');
      return `<div class="snap"><div class="snap-title">📁 ${T('快照', 'snapshot')} ${abbrev(h)}${repo.decoStr(h) ? '<span class="deco">' + esc(repo.decoStr(h)) + '</span>' : ''}</div><div class="snap-msg">${esc(c.message.split('\n')[0])}</div><ul>${files}${deleted}</ul></div>`;
    }).join('');
    const human = n => n < 1024 ? n + ' B' : (n / 1024).toFixed(1) + ' KB';
    return `<div class="size-compare"><div><span>${T('若每次提交都整个复制文件夹：', 'Copying the whole folder at every commit:')}</span><b>${human(fullCopyBytes)}</b></div><div><span>${T('git 对象库实际存储的文件内容：', 'File content git actually stores:')}</span><b>${human(uniqueBytes)}</b></div><div class="muted">${T(`共 ${all.length} 个提交，${blobs.size} 个不同的 blob。相同内容的文件只存一份，这就是“共享”的意思。`, `${all.length} commit${all.length === 1 ? '' : 's'}, ${blobs.size} distinct blob${blobs.size === 1 ? '' : 's'}. Files with identical content are stored only once: that's what “shared” means.`)}</div></div><div class="snaps">${cards}</div>`;
  }

  global.GitAnalogy = { explain, snapshotsHtml, traceHtml, table: A };
})(typeof window !== 'undefined' ? window : globalThis);
