// 浏览器冒烟测试：加载页面、执行命令、检查无 JS 错误、截图
const path = require('path');
const { chromium } = require('/tmp/pw/node_modules/playwright');
const http = require('http'); const fs = require('fs');
const root = path.resolve(__dirname, '..');
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml', '.png': 'image/png' };
const server = http.createServer((req, res) => { let p = decodeURIComponent(req.url.split('?')[0]); if (p === '/') p = '/index.html'; const f = path.join(root, p); if (!fs.existsSync(f) || fs.statSync(f).isDirectory()) { res.writeHead(404); return res.end('nf'); } res.writeHead(200, { 'Content-Type': MIME[path.extname(f)] || 'application/octet-stream' }); fs.createReadStream(f).pipe(res); });
(async () => {
  await new Promise(r => server.listen(8765, r));
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
  const page = await browser.newPage({ viewport: { width: 1500, height: 900 } });
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
  await page.goto('http://localhost:8765/#c1-2');
  await page.waitForSelector('#term-input');
  const type = async (cmd) => { await page.fill('#term-input', cmd); await page.press('#term-input', 'Enter'); await page.waitForTimeout(60); };
  await type('echo "# 项目说明" > README.md');
  await type('git add .');
  await type('git status');
  await type('git commit -m "第一次提交"');
  await page.waitForTimeout(200);
  const doneVisible = await page.$eval('#level-done', el => !el.classList.contains('hidden'));
  const tasksDone = await page.$$eval('#task-list li.done', els => els.length);
  console.log('tasks done:', tasksDone, 'level done shown:', doneVisible);
  await page.click('.tab[data-tab="analogy"]');
  await page.waitForTimeout(100);
  const analogy = await page.$eval('#analogy-card', el => el.innerText.slice(0, 80));
  console.log('analogy:', analogy.replace(/\n/g, ' '));
  await page.click('.tab[data-tab="graph"]');
  await page.screenshot({ path: '/tmp/claude-0/-home-user-gitgame/9b71a6b9-7f35-59a3-8136-f02b66bef4c1/scratchpad/shot1.png' });
  // 编辑器 + 冲突关
  await page.goto('http://localhost:8765/#c4-1');
  await page.waitForTimeout(200);
  await type('git merge feature');
  await type('edit greeting.js');
  await page.waitForSelector('#editor-modal:not(.hidden)');
  await page.fill('#editor-text', 'export function greet(name) {\n  return "Hi, " + name.trim() + "!";\n}\n');
  await page.click('#editor-save');
  await type('git add greeting.js');
  await type('git commit -m "merge"');
  await page.waitForTimeout(200);
  console.log('conflict level tasks done:', await page.$$eval('#task-list li.done', els => els.length));
  // 无 -m 的 commit 打开编辑器
  await page.goto('http://localhost:8765/#c1-3');
  await page.waitForTimeout(200);
  await type('echo "x" > utils.js && git add utils.js');
  await type('git commit');
  await page.waitForSelector('#editor-modal:not(.hidden)');
  await page.fill('#editor-text', 'add utils\n');
  await page.click('#editor-save');
  await page.waitForTimeout(100);
  const termText = await page.$eval('#term-output', el => el.innerText);
  console.log('commit via editor:', /\[main [0-9a-f]{7}\] add utils/.test(termText));
  // 多人标签 + 沙盒按钮
  await page.goto('http://localhost:8765/#sandbox');
  await page.waitForTimeout(300);
  await page.click('.tab[data-tab="multi"]');
  const btns = await page.$$('#multi-actions button');
  console.log('sandbox actions:', btns.length);
  await btns[0].click(); await page.waitForTimeout(200);
  await type('git pull');
  await page.waitForTimeout(100);
  await page.screenshot({ path: '/tmp/claude-0/-home-user-gitgame/9b71a6b9-7f35-59a3-8136-f02b66bef4c1/scratchpad/shot2.png' });
  const multiText = await page.$eval('#multi-repos', el => el.innerText);
  console.log('multi repos listed:', (multiText.match(/仓库|服务器/g) || []).length);
  console.log('errors:', errors.length ? errors : 'none');
  await browser.close(); server.close();
  process.exit(errors.length ? 1 : 0);
})().catch(e => { console.error(e); process.exit(1); });
